name: Terraform EAC EKS demo

on:
  push:
    branches:
      - main  # Change this to your main branch name if different
  repository_dispatch:
    types: [trigger-k8s-apply]
    
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.11

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: AWS 
      shell: bash
      run: |
        env
        aws s3 ls

    - name: Terraform Init
      run: |
      cd terraform
      terraform init

    - name: Terraform Validate
      run: |
      cd terraform
      terraform validate

    - name: Terraform Plan
      run: |
      cd terraform
      terraform plan -out=tfplan

    - name: Terraform Apply
      run: |
      cd terraform
      terraform apply --auto-approve

    - name: Archive Terraform Plan
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: tfplan
        path: terraform/tfplan
