name: Terraform EAC Chaos Creation

on:
  push:
    branches:
      - main  # Change this to your main branch name if different
  repository_dispatch:
    types: [trigger-k8s-apply]
    
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.1.7

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: AWS 
      shell: bash
      run: |
        env
        aws s3 ls

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      env:
        TF_VAR_mysql_username: ${{ secrets.TF_VAR_MYSQL_USERNAME }}
        TF_VAR_mysql_password: ${{ secrets.TF_VAR_MYSQL_PASSWORD }}
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      env:
        TF_VAR_mysql_username: ${{ secrets.TF_VAR_MYSQL_USERNAME }}
        TF_VAR_mysql_password: ${{ secrets.TF_VAR_MYSQL_PASSWORD }}
      run: terraform apply --auto-approve

    - name: Get Terraform output
      run: |
        echo "DB_HOSTNAME=$(terraform output -raw aurora_endpoint)"
        echo "DB_HOSTNAME=$(terraform output -raw aurora_endpoint)" >> $GITHUB_ENV

    - name: Checkout config repo
      uses: actions/checkout@v4
      with:
        repository: yletter/config-store
        token: ${{ secrets.YGITHUB_TOKEN }}
        path: config-store

    - name: Update config file
      run: |
        echo "DB_HOSTNAME = " $DB_HOSTNAME
        pwd
        ls -R
        ls -R ..
        cd config-store
        sed -i "s/^mysql\.hostname=.*/mysql.hostname=$DB_HOSTNAME/" application.properties

    - name: Commit and push changes
      run: |
        pwd
        ls -R
        cd config-store
        git config user.name "yuvarajengineer"
        git config user.email "yuvarajengineer@gmail.com"
        git add application.properties
        git commit -m "Updated MySQL hostname to ${{ env.DB_HOSTNAME }}"
        git push origin main

    - name: Archive Terraform Plan
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: terraform/tfplan
