name: Terraform EAC Chaos Destroy
on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-k8s-destroy]
    
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.11

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: AWS 
      shell: bash
      run: |
        env
        aws s3 ls

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      env:
        TF_VAR_mysql_username: ${{ secrets.TF_VAR_MYSQL_USERNAME }}
        TF_VAR_mysql_password: ${{ secrets.TF_VAR_MYSQL_PASSWORD }}
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      env:
        TF_VAR_mysql_username: ${{ secrets.TF_VAR_MYSQL_USERNAME }}
        TF_VAR_mysql_password: ${{ secrets.TF_VAR_MYSQL_PASSWORD }}
      run: terraform destroy --auto-approve

    - name: Archive Terraform Plan
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: terraform/tfplan
