name: Terraform EAC Chaos Destroy
on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-k8s-destroy]
    
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.11

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: AWS 
      shell: bash
      run: |
        env
        aws s3 ls

    - name: Deploy Applications
      run: |
        # Install Kubectl
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        kubectl version --client
    
        # Install Helm
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        helm version

        cd ..
        mkdir deploy
        cd deploy
        aws eks update-kubeconfig --region us-east-1 --name chaos-cluster
        
        git clone https://github.com/yletter/chaos-helm

        cd chaos-helm
        cd charts
        kubectl delete ns dd
        kubectl delete ns app
        sleep 30

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      env:
        TF_VAR_mysql_username: ${{ secrets.TF_VAR_MYSQL_USERNAME }}
        TF_VAR_mysql_password: ${{ secrets.TF_VAR_MYSQL_PASSWORD }}
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      env:
        TF_VAR_mysql_username: ${{ secrets.TF_VAR_MYSQL_USERNAME }}
        TF_VAR_mysql_password: ${{ secrets.TF_VAR_MYSQL_PASSWORD }}
      run: terraform destroy --auto-approve

    - name: Archive Terraform Plan
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: terraform/tfplan
